### ISSUE TITLE
tclobj

### ISSUE THREAD

**Issue by ezx** [flightaware/speedtables#36]
Can the 'tclobj' datatype be used for anything right now? I am specifically looking for command substitution where the value with datatype of 'tclobj' or similar is automatically substituted with the return value of the command that the value was set to (like another ctable search etc, leading to nice nested tables with much more complex data structures). The same functionality is achievable with the '-code' option but that is much more verbose. I am just curious if 'tclobj' can be put to a good use. :)

Thanks

**Comment by resuna** [comment]
If you're storing something like a code fragment for a callback in a speedtable, storing it as a Tcl_Obj will allow the compiled code to be kept "live" so it doesn't have to be recompiled every time it's hit. Same if you're storing something that'll be used frequently as a list. Think of it as a way of avoiding shimmering.
