### ISSUE TITLE
Incompatibility between compare "in" operator in native speedtables versus stapi-based postgres version

### ISSUE THREAD

**Issue by lehenbauer** [flightaware/speedtables#64]
Small bug in speedtables' stapi SQL translation when using the `in` operator: the documentation (https://flightaware.github.io/speedtables/manual/ch05.html) says that `in` in a `-compare` switch should be `{in field valueList}` but https://github.com/flightaware/speedtables/blob/master/stapi/client/pgsql.tcl#L871 treats it as `{in field value1 value2 value3...}`; we think that L871 should be `foreach v [lindex $tuple end]`

**Comment by resuna** [comment]
Fixed in branch "issue64".

**Comment by bovine** [comment]
merged into master for upcoming 1.9.4 release
