### ISSUE TITLE
Pacakge versions for 1.13.18 say 1.13.17

### ISSUE THREAD

**Issue by gahr** [flightaware/speedtables#85]
https://github.com/flightaware/speedtables/commit/3dec9030964aaf75b6378582f9b127b639b03cd3

**Comment by resuna** [comment]
Also package versions for 1.13.14 say 1.13.12.

Since I can't seem to delete tags on github, I couldn't re-release 1.13.17 after fixing the package versions. This also means I'll have to re-re-release it as v1.13.19. Is this a big deal for you?

**Comment by gahr** [comment]
No, as long as the tag matches the package version.. now that I think of it, speedtables doesn't have any shared library named after the package version, so this is not a big issue.. might be confusing for users, though, so I'd rather wait for 1.13.19.

**Comment by resuna** [comment]
Unless it's a big deal I am not planning on releasing a new version just to fix this.

**Comment by gahr** [comment]
I guess I can use 1.13.17 :D

**Comment by gahr** [comment]
Oh, you removed that commit.

**Comment by resuna** [comment]
The reason for v1.13.18 was because v1.13.17 was on the wrong branch.

I think I have performed the necessary reposurgery.

**Comment by gahr** [comment]
Thanks a lot, looks good!
